---

- name: Install DokuWiki
  tags:
    - setup-all
    - setup-dokuwiki
    - install-all
    - install-dokuwiki
  block:
    - name: Run DokuWiki validation tasks
      when: dokuwiki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Run DokuWiki installation tasks
      when: dokuwiki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Uninstall DokuWiki
  tags:
    - setup-all
    - setup-dokuwiki
  block:
    - name: Run DokuWiki uninstallation tasks
      when: not dokuwiki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
